http://localhost:8080/recipe/
@Content-type: application/json


%%%

# Duration: 45 ms
# URL: http://localhost:8080/recipe/

# HTTP/1.1 200

@Content-Type: application/json;charset=UTF-8
@Transfer-Encoding: chunked
@Date: Sun, 19 May 2019 12:47:06 GMT

[]